[package]
name = "can-pil-linux-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-can = "0.4.1"
libc = "0.2.149"
nix = {version = "0.27.1", features = ["net"]}
socketcan = "3.2.0"
